ci: move failing bash logic into github logic

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -61,13 +61,12 @@ jobs:
     runs-on: ubuntu-latest
     needs: pytest_fast_run
     steps:
-      - name: Build and test
+      - name: Fail job if pytest failed
+        if: needs.pytest_fast_run.outputs.pytest_exit_code != '0'
         shell: bash
         run: |
-          if [ "${{ needs.pytest_fast_run.outputs.pytest_exit_code }}" = "0" ]; then
-            echo "Pytest failed"
-            exit 1
-          fi
+          echo "Pytest failed"
+          exit 1
 
   linux:
     runs-on: ${{ matrix.platform.runner }}
