ci: intermediate job parsing pytest result

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -19,8 +19,8 @@ permissions:
   contents: read
 
 jobs:
-  pytest_fast:
-    name: Fast reject on pytest before building wheels
+  pytest_run:
+    name: Run pytest for fast reject before building wheels
     runs-on: ubuntu-latest
     outputs:
       pytest_exit_code: ${{ steps.result.outputs.pytest_exit_code }}
@@ -55,10 +55,22 @@ jobs:
           echo "pytest_exit_code=$?" >> "$GITHUB_OUTPUT"
           set -e
 
+  pytest_ok:
+    name: Convert pytest run to 'needs' for wheels build
+    runs-on: ubuntu-latest
+    needs: pytest_fast
+    steps:
+      - name: Build and test
+        shell: bash
+        run: |
+          if [ "${{ needs.pytest_fast.outputs.pytest_exit_code }}" = "0" ]; then
+            echo "Pytest failed"
+            exit 1
+          else
+
   linux:
     runs-on: ${{ matrix.platform.runner }}
-    needs: pytest_fast
-    if: needs.pytest_fast.outputs.pytest_exit_code == '0'
+    needs: pytest_ok
     strategy:
       matrix:
         platform:
@@ -95,8 +107,7 @@ jobs:
 
   musllinux:
     runs-on: ${{ matrix.platform.runner }}
-    needs: pytest_fast
-    if: needs.pytest_fast.outputs.pytest_exit_code == '0'
+    needs: pytest_ok
     strategy:
       matrix:
         platform:
@@ -129,8 +140,7 @@ jobs:
 
   windows:
     runs-on: ${{ matrix.platform.runner }}
-    needs: pytest_fast
-    if: needs.pytest_fast.outputs.pytest_exit_code == '0'
+    needs: pytest_ok
     strategy:
       matrix:
         platform:
@@ -159,8 +169,7 @@ jobs:
 
   macos:
     runs-on: ${{ matrix.platform.runner }}
-    needs: pytest_fast
-    if: needs.pytest_fast.outputs.pytest_exit_code == '0'
+    needs: pytest_ok
     strategy:
       matrix:
         platform:
@@ -188,8 +197,7 @@ jobs:
 
   sdist:
     runs-on: ubuntu-latest
-    needs: pytest_fast
-    if: needs.pytest_fast.outputs.pytest_exit_code == '0'
+    needs: pytest_ok
     steps:
       - uses: actions/checkout@v4
       - name: Build sdist
