ci: try splitting build and test steps

diff --git a/.github/workflows/pytest_ubuntu.yml b/.github/workflows/pytest_ubuntu.yml
--- a/.github/workflows/pytest_ubuntu.yml
+++ b/.github/workflows/pytest_ubuntu.yml
@@ -31,11 +31,15 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
-      - name: Run tests
+      - name: Build maturin dev
         shell: bash
         run: |
-          set -x # Fail on error
+          set -e # Fail on error
           uv venv
           source .venv/bin/activate
           maturin develop --uv --extras dev
-          pytest
+
+      - name: Run tests
+        shell: bash
+        run: |
+          pytest -s -v
